### ISSUE TITLE
Error while doing migration

### ISSUE THREAD

**Issue by rahmonov** [hnarayanan/kubernetes-django#11]
I am getting this error while migrating:

    Is the server running on host "127.0.0.1" and accepting TCP/IP connections on port 5432?

I think that is because `DATABASE_SERVICE_HOST` env variable is not set.
How can I fix this?

**Comment by hnarayanan** [comment]
I think you may be running steps out of order? (Try looking at the instructions to see if this might be the case.) You need to setup the postgres pod first before attempting to setup django.

**Comment by rahmonov** [comment]
Thank you! I deleted everything app related and then redid. Now everything works. But I don't understand one thing. How was `DATABASE_SERVICE_HOST` set? How was the app service be able to talk to the database service?

**Comment by hnarayanan** [comment]
This is part of a very useful feature that Kubernetes provides. When a Pod is run on a Node, the kubelet adds a set of environment variables for each active Service: https://kubernetes.io/docs/user-guide/services/#environment-variables

**Comment by rahmonov** [comment]
@hnarayanan thank you for this tutorial and help! It is great. I am going to tweet it out.

**Comment by hnarayanan** [comment]
Thank you, I am glad you found it useful. There is also a related blog post which might be interesting to you too: https://harishnarayanan.org/writing/kubernetes-django/
