### ISSUE TITLE
Unpin the postgresql install

### ISSUE THREAD

**Issue by clebio** [hnarayanan/kubernetes-django#7]
Hi, thanks for the awesome blog post (came here from HN). It's inspired me to finally get around to trying out GCE.

When I run

```
docker build -t hnarayanan/postgresql:9.5  .
```

I'm getting the following errors:

``` bash
E: Version '9.5.0-1.pgdg80+2' for 'postgresql-9.5' was not found
E: Version '9.5.0-1.pgdg80+2' for 'postgresql-contrib-9.5' was not found
```

If I just unpin the postgres versions in the `apt-get install`s, the image builds fine:

``` diff
diff --git i/containers/database/Dockerfile w/containers/database/Dockerfile
index 5058b6b..aa09a76 100644
--- i/containers/database/Dockerfile
+++ w/containers/database/Dockerfile
@@ -31,8 +31,8 @@ RUN apt-get update \
        && apt-get install -y postgresql-common \
        && sed -ri 's/#(create_main_cluster) .*$/\1 = false/' /etc/postgresql-common/createcluster.conf \
        && apt-get install -y \
-               postgresql-$PG_MAJOR=$PG_VERSION \
-               postgresql-contrib-$PG_MAJOR=$PG_VERSION \
+               postgresql-$PG_MAJOR \
+               postgresql-contrib-$PG_MAJOR \
        && rm -rf /var/lib/apt/lists/*
```

**Comment by hnarayanan** [comment]
I see what you're trying to do, but I essentially copied in the official PostgreSQL Docker image. I am curious to find out how this could crop up.

 Going to pull it in once more, and if I can't make sense of it, will instead merge your patch. So thank you!

**Comment by tdumitrescu** [comment]
FWIW this happened again with the latest.

```
E: Version '9.5.2-1.pgdg80+1' for 'postgresql-9.5' was not found
E: Version '9.5.2-1.pgdg80+1' for 'postgresql-contrib-9.5' was not found
```

Bumping to `9.5.3-1.pgdg80+1` fixes it but surely the proposal in here is more future-proof?

**Comment by hnarayanan** [comment]
I agree. The proposed solution is the correct way to do this. Will work it in.

**Comment by hnarayanan** [comment]
This has now been fixed by @tdumitrescu!
