### ISSUE TITLE
Step for static assets on CDN missing some dependencies

### ISSUE THREAD

**Issue by clebio** [hnarayanan/kubernetes-django#8]
When you get to the step 

```
./manage.py collectstatic 
```

you'll need Django installed. Using a Python virtualenv, something like

```
mkvirtualenv django
pip install django
```

Unfortunately, you also need `psycopg2` which suffers from the leaky abstraction of needing Postgres in the host OS. So, on a mac, you also need to do

```
brew install postgresql
pip install psycopg2
```

Woe unto you if you also need to go install [Homebrew](http://brew.sh/).

**Comment by hnarayanan** [comment]
(I pity the fool.)

Thank you for pointing this out. 👍  I knew this would pop up sooner or later, and I'll augment the docs to reflect this.

**Comment by hnarayanan** [comment]
I think I fixed it in a reasonably elegant fashion. Please reopen this if it is not sufficient.

**Comment by clebio** [comment]
I like it. Well played!
